
import ProviderContext from '@/app/Provider'
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Products - BATRA',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ProviderContext>
      <div>
        {children}
      </div>
    </ProviderContext>
  )
}
