import NavBar from '@/components/NavBarAdmin/NavBar'
import type { Metadata } from 'next'
export const metadata: Metadata = {
    title: 'Admin - BATRA',
    description: 'Generated by create next app',
}
export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <div className='container mx-auto mb-10'>
            <h3 className='font-bold text-3xl tracking-widest pl-10 mb-10'>Admin</h3>
            <div className='nav_bar__admin flex justify-between'>
                <div className='md:w-[15%] sm:w-[20%]'>
                    <NavBar />
                </div>
                <div className='md:w-[85%] table_admin sm:w-[80%]'>
                    {children}
                </div>
            </div>
        </div>
    )
}
