
import type { Metadata } from 'next'
export const metadata: Metadata = {
  title: 'Saigon FW - 2023',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div>
        {children}
    </div>
  )
}
